<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZendPress\Api\CollectionManager' => __DIR__ . '/src/ZendPress/Api/CollectionManager.php',
    'ZendPress\Api\Filter' => __DIR__ . '/src/ZendPress/Api/Filter.php',
    'ZendPress\Api\EntityManager' => __DIR__ . '/src/ZendPress/Api/EntityManager.php',
    'ZendPress\Structure\EntityInterface' => __DIR__ . '/src/ZendPress/Structure/EntityInterface.php',
    'ZendPress\Structure\ManagerInterface' => __DIR__ . '/src/ZendPress/Structure/ManagerInterface.php',
    'ZendPress\Service\Client' => __DIR__ . '/src/ZendPress/Service/Client.php',
    'ZendPress\Service\Hydrator' => __DIR__ . '/src/ZendPress/Service/Hydrator.php',
    'ZendPress\Service\Locator' => __DIR__ . '/src/ZendPress/Service/Locator.php',
    'ZendPress\Service\HttpAdapter' => __DIR__ . '/src/ZendPress/Service/HttpAdapter.php',
    'ZendPress\Entity\BaseEntity' => __DIR__ . '/src/ZendPress/Entity/BaseEntity.php',
    'ZendPress\Entity\Media' => __DIR__ . '/src/ZendPress/Entity/Media.php',
    'ZendPress\Entity\Post' => __DIR__ . '/src/ZendPress/Entity/Post.php',
    'ZendPress\Entity\Author' => __DIR__ . '/src/ZendPress/Entity/Author.php',
    'ZendPress\Factory\CollectionManagerFactory' => __DIR__ . '/src/ZendPress/Factory/CollectionManagerFactory.php',
    'ZendPress\Factory\HttpAdapterFactory' => __DIR__ . '/src/ZendPress/Factory/HttpAdapterFactory.php',
    'ZendPress\Factory\ClientFactory' => __DIR__ . '/src/ZendPress/Factory/ClientFactory.php',
    'ZendPress\Factory\EntityManagerFactory' => __DIR__ . '/src/ZendPress/Factory/EntityManagerFactory.php',
    'ZendPress\Factory\FilterFactory' => __DIR__ . '/src/ZendPress/Factory/FilterFactory.php',
    'ZendPress\Factory\PostFactory' => __DIR__ . '/src/ZendPress/Factory/PostFactory.php',
);
